[package]
name = "roster-to-ics"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.28", features = ["derive"] }
ics = "0.5.8"
calamine = "0.26.1"
anyhow = "1.0.95"
chrono = "0.4.39"
